#!/usr/bin/env python3
"""Generate fixed THP test vectors (from the reference implementations) for the
monero unit test. Deterministic: seeded, so re-running reproduces the file."""
import os, sys, hmac, hashlib, random, zlib

sys.path.insert(0, os.path.expanduser("~/feather-safe7/ref/trezor-firmware/python/src"))
from trezorlib.thp import curve25519 as ref_c25519, cpace as ref_cpace
from trezorlib.thp.message import Message
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

rnd = random.Random(20260730)
rb = lambda n: bytes(rnd.getrandbits(8) for _ in range(n))

out = []
w = out.append

w("// Generated by contrib/thp/gen_vectors.py from the trezor-firmware reference")
w("// implementation (trezorlib.thp) and the `cryptography` package.")
w("// Do not edit by hand; regenerate if the protocol changes.")
w("")
w("#pragma once")
w("#include <cstdint>")
w("namespace thp_vectors {")
w("")
w("struct HexPair { const char *in; const char *out; };")
w("struct HexTriple { const char *a; const char *b; const char *out; };")
w("")

# --- x25519 scalarmult ---
w("// x25519_scalarmult(scalar, point)")
w("static const HexTriple X25519_MUL[] = {")
for _ in range(12):
    s, p = rb(32), rb(32)
    w('  {"%s", "%s", "%s"},' % (s.hex(), p.hex(), ref_c25519.multiply(s, p).hex()))
w("};")
w("")

# --- elligator2 ---
w("// elligator2(input)")
w("static const HexPair ELLIGATOR2[] = {")
for _ in range(12):
    u = rb(32)
    w('  {"%s", "%s"},' % (u.hex(), ref_c25519.elligator2(u).hex()))
w("};")
w("")


def noise_hkdf(ck, inp):
    tk = hmac.new(ck, inp, hashlib.sha256).digest()
    o1 = hmac.new(tk, b"\x01", hashlib.sha256).digest()
    o2 = hmac.new(tk, o1 + b"\x02", hashlib.sha256).digest()
    return o1 + o2


w("// hkdf(ck, input) -> out1 || out2")
w("static const HexTriple HKDF[] = {")
for n in (0, 1, 32, 64):
    ck, inp = rb(32), rb(n)
    w('  {"%s", "%s", "%s"},' % (ck.hex(), inp.hex(), noise_hkdf(ck, inp).hex()))
w("};")
w("")

# --- AES-256-GCM with Noise nonce ---
w("struct GcmVector { const char *key; uint64_t nonce; const char *ad; const char *pt; const char *ct; };")
w("static const GcmVector AES_GCM[] = {")
for n in (0, 1, 2, 1234567890123):
    key, ad, pt = rb(32), rb(rnd.choice([0, 16, 32])), rb(rnd.choice([0, 1, 48, 130]))
    iv = b"\x00" * 4 + n.to_bytes(8, "big")
    ct = AESGCM(key).encrypt(iv, pt, ad if ad else None)
    w('  {"%s", %dULL, "%s", "%s", "%s"},' % (key.hex(), n, ad.hex(), pt.hex(), ct.hex()))
w("};")
w("")

# --- CPace generator ---
w("// cpace_generator(code, handshake_hash)")
w("struct CpaceVector { const char *code; const char *hh; const char *gen; };")
w("static const CpaceVector CPACE_GEN[] = {")
for _ in range(8):
    code = "%06d" % rnd.randrange(1000000)
    hh = rb(32)
    gen = ref_cpace._generator(prs=code.encode(), ci=hh).hex()
    w('  {"%s", "%s", "%s"},' % (code, hh.hex(), gen))
w("};")
w("")

# --- CRC32 ---
w("static const HexPair CRC32[] = {")
for n in (0, 1, 5, 64, 300):
    d = rb(n)
    w('  {"%s", "%08x"},' % (d.hex(), zlib.crc32(d)))
w("};")
w("")

# --- Message.to_bytes ---
w("struct MsgVector { uint8_t ctrl; uint16_t cid; const char *data; const char *encoded; };")
w("static const MsgVector MESSAGES[] = {")
for ctrl in (0x00, 0x02, 0x04, 0x14, 0x20, 0x40, 0x41, 0x43):
    for n in (0, 1, 55, 59, 60, 120):
        cid = rnd.randrange(0x10000)
        d = rb(n)
        w('  {0x%02x, 0x%04x, "%s", "%s"},' % (ctrl, cid, d.hex(),
                                               Message(ctrl, cid, d).to_bytes().hex()))
w("};")
w("")

w("} // namespace thp_vectors")

path = os.path.expanduser(
    "~/feather-safe7/feather/monero/tests/unit_tests/trezor_thp_vectors.h")
open(path, "w").write("\n".join(out) + "\n")
print("wrote", path, len(out), "lines")
